// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: bf853f1c663903e3ee35935189760191f1c45e1c

package data

import (
	_ "embed"
	"encoding/json"

	"github.com/go-enry/go-enry/v2/data/types"
)

//go:embed languageInfo.go.json
var langInfo []byte

func init() {
	json.Unmarshal(langInfo, &LanguageInfoByID)
}

type LanguageInfo = types.LanguageInfo

// LanguageInfoByID allows accessing LanguageInfo by a language's ID.
var LanguageInfoByID = map[int]LanguageInfo{}
