// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: bf853f1c663903e3ee35935189760191f1c45e1c

package data

import (
	_ "embed"
	"encoding/json"

	"github.com/go-enry/go-enry/v2/data/types"
)

//go:embed type.go.json
var langType []byte

func init() {
	json.Unmarshal(langType, &LanguagesType)
}

type Type = types.Type

var LanguagesType = map[string]int{}
